language: bash
services: docker

env:
    - VERSION=2.10

install:
    - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
    - cd "$VERSION"
    - image="ualibraries/swift_dev:${VERSION}"

script:
    - docker build -t "$image" .
    - ~/official-images/test/run.sh "$image"


after_script:
    - docker images
